name: Build FEX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python and dependencies
        run: |
          python3 -m pip install --break-system-packages packaging setuptools

      - name: Install Dependencies
        run: |
          brew install cmake ninja pkg-config llvm

      - name: Configure CMake
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_LTO=OFF

      - name: Build FEX
        run: |
          cmake --build build --config Release
